### ISSUE TITLE
control: text

### ISSUE THREAD

**Issue by keshrath** [leadedge/SpoutControls#1]
Hello,

First, thanks for the great work and the wonderful plugin.

I have noticed that there might be a bug with text field controls. I tried out the CircleLineDemo and wanted to use the userText to show some text on the screen.

.) I changed the text value from "" to some word, but it didn't show up in Resolume.

With the SpoutController.exe it worked, so the plugin shouldn't be the problem.

Best regards
Keshrath

**Comment by leadedge** [comment]
There is a mistake in the sketch  -

spout.CreateSpoutControl("User Text", "text");
should be
spout.CreateSpoutControl("User text", "text");

Also it is not printing the text or loading a font, so use SpoutBox.pde as a template instead.

**Comment by keshrath** [comment]
It's not about displaying it in processing. This works perfectly fine.

It's just that the Resoulme controls are always empty at the start, but the SpoutController.exe shows the predefined value.

So you can't set a default text?

{
        "NAME": "UserText",
    "TYPE": "text",
    "TEXT": "default"
},

spout.CreateSpoutControl("UserText", "text", "default");

**Comment by leadedge** [comment]
OK I found it in the JSON parse function which set the string to "".

Even if this was fixed, a problem remains that the default text won't show up when you load the plugin until you change a control and CheckSpoutControls comes back positive. There are a few more anomalies that I am working through, but meanwhile the current version should be stable.
